name: Bug report
description: Technical issue with https://devdocs.magento.com/
labels: ["bug"]
assignees:
  - dshevtsov
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this issue!
        GitHub Issues in this repo should relate to this project's codebase.
        Before submitting this issue, please make sure you are complying with our [Code of Conduct](https://github.com/magento/devdocs/blob/master/.github/CODE_OF_CONDUCT.md):
        Issues that do not comply with our Code of Conduct or do not contain enough information may be closed at the maintainers' discretion.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: |
        Tell us what happened. Include error messages and issues.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        Tell us what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Provide a set of clear steps to reproduce this bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Describe your environment.
        Provide all the details that will help us to reproduce the bug.
      value: |
        - Browser:
        - OS:
    validations:
      required: true
