---
title: ConfigurableProductGraphQl
release: 2.4.3
content: |-
  **ConfigurableProductGraphQl** provides type and resolver information for the GraphQl module
  to generate configurable product information.
