---
title: InventoryCatalogSearchConfigurableProduct
release: 2.4.3
content: The Magento_InventoryCatalogSearchConfigurableProduct module adds multi-sourcing
  capabilities to the Magento's CatalogSearch module
