---
title: ConfigurableRequisitionListGraphQl
release: 2.4.3
content: "**ConfigurableRequisitionListGraphQl** provides GraphQL schema and resolvers
  for the requisition list module to extend and implement configurable products in
  requisition list"
